version: 2.1
workflows:
  build_and_test:
    jobs:
      - build
      - test:
        requires:
          - build
jobs:
  build:
    docker: 
      - image: cimg/node:14.10.1 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - restore_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn global add node-gyp && yarn install
      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}      
          paths:
            - ./node_modules
  test:
    docker:
      - image: cimg/node:14.10.1 # the primary container, where your job's commands are run
    steps: 
      - checkout
      - restore_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn lint && yarn format:check
      - run: yarn test:ci
      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}      
          paths:
            - ./node_modules