version: 2.1
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
jobs:
  build:
    docker: 
      - image: cimg/node:14.10.1
    steps:
      - checkout
      - restore_cache:
          key: yarn-packages-v2{{ checksum "yarn.lock" }}
      - run: yarn global add node-gyp && yarn install
      - save_cache:
          key: yarn-packages-v2{{ checksum "yarn.lock" }}      
          paths:
            - ./node_modules
  test:
    docker:
      - image: cimg/node:14.10.1
    steps: 
      - checkout
      - restore_cache:
          key: yarn-packages-v2{{ checksum "yarn.lock" }}
      - run: yarn lint && yarn format:check
      - run: yarn test:ci
      - save_cache:
          key: yarn-packages-v2{{ checksum "yarn.lock" }}      
          paths:
            - ./node_modules